### ISSUE TITLE
Provide Validation API (JSR-349) Support

### ISSUE THREAD

**Issue by codechimp** [zalando-incubator/java-sproc-wrapper#18]
Why do we support only the  NotNull constraint in the Sproc Wrapper? Having full support of JSR-349 would ease the Sproc parameter validation (before a DB request is issued) a lot and reduce the of boilderplate validation code in the SprocService implememtations.

**Comment by valgog** [comment]
This is a good idea. I will close the request though, as I do not know who should implement it.

**Comment by valgog** [comment]
Ha, I even cannot close it :D
