### ISSUE TITLE
Upgrade postgres-jdbc dependency

### ISSUE THREAD

**Issue by musikara** [zalando-incubator/java-sproc-wrapper#31]
9.4-1207-41 is not compatible with 9.3, which is current version of the sprocwrapper.

**Comment by Jan-M** [comment]
The java-sproc-wrapper is not compatible with the new PostgreSQL JDBC versions as the type mapper relies heavily on the returned object strucuture which unfortunately changed (we noticed this only recently).

**Comment by jonnyry** [comment]
Any update on this?

**Comment by valgog** [comment]
I am afraid not. Will try to have a look on this.

**Comment by robjkc** [comment]
What is the impact of this issue.  I've just started using sprocwrapper yesterday using PostgreSQL version 9.5 with JDBC driver 9.4-1205.  I haven't run into any issues yet but was wondering if I might.  Thanks!

**Comment by vadeg** [comment]
I have updated version (see #41 )

**Comment by vadeg** [comment]
Version updated to 42.1.1. See PR #41
