### ISSUE TITLE
StoredProcedure is not thread safe but used in multithreaded context

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando-incubator/java-sproc-wrapper#37]
`StoredProcedure` is wrapped in `Call` (which implements `Callable`) and passed to thread pool. 
If two concurrent threads try to execute `Callable` one of them could observe uninitialized types in `StoredProcedure.getTypes()` 

See `StoredProcedure.executeInParallel()`
https://github.com/zalando-incubator/java-sproc-wrapper/blob/master/src/main/java/de/zalando/sprocwrapper/proxy/StoredProcedure.java#L590

and `StoredProcedure.getTypes()` 
https://github.com/zalando-incubator/java-sproc-wrapper/blob/master/src/main/java/de/zalando/sprocwrapper/proxy/StoredProcedure.java#L218

**Comment by AlexanderYastrebov** [comment]
From client POV this could be observed as:

`org.postgresql.util.PSQLException: Unsupported Types value: 0`

**Comment by vadeg** [comment]
Can someone make a new release with this fix?
